#!/usr/bin/env bash
# Interactive .env writer for Axia.
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env"
EXAMPLE_FILE=".env.example"

if [[ -f "$ENV_FILE" ]]; then
    echo ".env already exists. Overwrite? [y/N]"
    read -r ans
    ans_lc=$(printf '%s' "$ans" | tr '[:upper:]' '[:lower:]')
    [[ "$ans_lc" == "y" || "$ans_lc" == "yes" ]] || { echo "Aborted."; exit 0; }
fi

echo ""
echo "=================================================================="
echo " Axia setup"
echo "=================================================================="
echo ""

# ---------------------------------------------------------------------------
# MongoDB mode
# ---------------------------------------------------------------------------
echo "Where should the MongoDB instance run?"
echo "  1) Local (docker-compose starts a mongo:7 container, seeds sample data)"
echo "  2) External (you provide a URI, e.g. MongoDB Atlas)"
read -rp "Choice [1]: " mongo_choice
mongo_choice=${mongo_choice:-1}

if [[ "$mongo_choice" == "2" ]]; then
    MONGODB_MODE="external"
    read -rp "MongoDB URI: " MONGODB_URI
    while [[ -z "$MONGODB_URI" ]]; do
        read -rp "  (required) MongoDB URI: " MONGODB_URI
    done
    read -rp "MongoDB database name [axia]: " MONGODB_DB
    MONGODB_DB=${MONGODB_DB:-axia}
    NEXT_PUBLIC_MONGODB_URI="$MONGODB_URI"
else
    MONGODB_MODE="local"
    MONGODB_URI="mongodb://mongo:27017"
    NEXT_PUBLIC_MONGODB_URI="mongodb://localhost:27017"
    MONGODB_DB="axia"
fi

# ---------------------------------------------------------------------------
# OpenAI
# ---------------------------------------------------------------------------
echo ""
echo "OpenAI API key (required for GPT-5 agents).  Leave empty to set later."
read -rp "OPENAI_API_KEY: " OPENAI_API_KEY
read -rp "Default OpenAI model [gpt-5-mini]: " OPENAI_DEFAULT_MODEL
OPENAI_DEFAULT_MODEL=${OPENAI_DEFAULT_MODEL:-gpt-5-mini}

# ---------------------------------------------------------------------------
# Model server (optional)
# ---------------------------------------------------------------------------
echo ""
echo "Fine-tuned model server URL (OPTIONAL)."
echo "  Leave empty to disable the Event Analyst agent."
echo "  Example: https://abc123.runpod.io or http://gpu-host:8000"
read -rp "MODEL_SERVER_URL: " MODEL_SERVER_URL

# ---------------------------------------------------------------------------
# Write .env
# ---------------------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
# Generated by make setup on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
MONGODB_MODE=$MONGODB_MODE
MONGODB_URI=$MONGODB_URI
MONGODB_DB=$MONGODB_DB
MONGODB_CORPUS_COLLECTION=sources
MONGODB_METADATA_COLLECTION=metadata_records

MODEL_SERVER_URL=$MODEL_SERVER_URL

OPENAI_API_KEY=$OPENAI_API_KEY
OPENAI_DEFAULT_MODEL=$OPENAI_DEFAULT_MODEL

SERVICE_HOST=0.0.0.0
SERVICE_PORT=8000
SERVICE_LOG_LEVEL=info
SERVICE_DEBUG=false

NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_MONGODB_URI=$NEXT_PUBLIC_MONGODB_URI
NEXT_PUBLIC_MONGODB_DB=$MONGODB_DB
NEXT_PUBLIC_MONGODB_MODE=$MONGODB_MODE
NEXT_PUBLIC_ALLOWED_FILE_TYPES=.json,.pkl
NEXT_PUBLIC_DEBUG=false
EOF

chmod 600 "$ENV_FILE"

echo ""
echo "Wrote $ENV_FILE."
echo ""
echo "Next steps:"
echo "  make up           # start the stack"
echo "  make logs         # follow logs"
echo "  make verify       # smoke-test the stack"
echo ""
if [[ -z "$OPENAI_API_KEY" ]]; then
    echo "  WARNING: OPENAI_API_KEY is empty. GPT-5 agents will fail."
fi
if [[ -z "$MODEL_SERVER_URL" ]]; then
    echo "  NOTE: MODEL_SERVER_URL is empty. Event Analyst agent is disabled."
fi
